### ISSUE TITLE
Different approach

### ISSUE THREAD

**Issue by SantoJambit** [blakeembrey/arity#9]
I got here via https://github.com/cucumber/cucumber-js/issues/514 and while doing some experiments I came up with a simpler approach, which seems to work for me and wanted to know if you see any issues with this:

```javascript
const wrappedFn = (...args) => originalFn.apply(this, args);
Object.defineProperty(wrappedFn, 'length', { value: intendedLength });
```

**Comment by blakeembrey** [comment]
Looks reasonable. I want to say the reason it was written this was is related to older JS systems, but I can't recall now. Thanks for sharing!

**Comment by blakeembrey** [comment]
Just verified. At the time this was written node 0.10 was the latest version (see `.travis.yml`). It does not let you do this:

```js
> Object.defineProperty(test, 'length', { value: 5 })
TypeError: Cannot redefine property: length
```
